server.port=8082

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=accountsdb
spring.webflux.base-path=/api/v1
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.data.redis.host=redis
spring.data.redis.port=6379
redis.cache.ttl-seconds=120

