server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.routes[0].id=accounts-service-route
spring.cloud.gateway.routes[0].uri=lb://accounts-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/accounts/**

spring.cloud.gateway.routes[1].id=credits-service-route
spring.cloud.gateway.routes[1].uri=lb://credits-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/credits/**

spring.cloud.gateway.routes[2].id=transactions-service-route
spring.cloud.gateway.routes[2].uri=lb://transactions-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/transactions/**

spring.cloud.gateway.routes[3].id=customer-service-route
spring.cloud.gateway.routes[3].uri=lb://customer-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/customers/**
