spring.application.name=api-gateway

spring.config.import=optional:configserver:http://localhost:8888
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.routes[0].id=accounts-service-route
spring.cloud.gateway.routes[0].uri=lb://accounts-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/accounts/**
spring.cloud.gateway.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.name=myCircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.fallbackUri=forward:/fallback/accounts

spring.cloud.gateway.routes[1].id=credits-service-route
spring.cloud.gateway.routes[1].uri=lb://credits-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/credits/**
spring.cloud.gateway.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.name=myCircuitBreaker
spring.cloud.gateway.routes[1].filters[0].args.fallbackUri=forward:/fallback/credits

spring.cloud.gateway.routes[2].id=transactions-service-route
spring.cloud.gateway.routes[2].uri=lb://transactions-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/transactions/**
spring.cloud.gateway.routes[2].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[2].filters[0].args.name=myCircuitBreaker
spring.cloud.gateway.routes[2].filters[0].args.fallbackUri=forward:/fallback/transactions

spring.cloud.gateway.routes[3].id=customer-service-route
spring.cloud.gateway.routes[3].uri=lb://customer-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/customers/**
spring.cloud.gateway.routes[3].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[3].filters[0].args.name=myCircuitBreaker
spring.cloud.gateway.routes[3].filters[0].args.fallbackUri=forward:/fallback/customers

spring.cloud.gateway.routes[4].id=yanki-service-route
spring.cloud.gateway.routes[4].uri=lb://yanki-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/yanki/**
spring.cloud.gateway.routes[4].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[4].filters[0].args.name=myCircuitBreaker
spring.cloud.gateway.routes[4].filters[0].args.fallbackUri=forward:/fallback/yanki

resilience4j.circuitbreaker.configs.default.sliding-window-size=10
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.configs.default.register-health-indicator=true

resilience4j.timelimiter.configs.default.timeout-duration=2s
resilience4j.timelimiter.configs.default.cancel-running-future=true
