server:
  port: 8081
spring:
  profiles:
    active: mongodb
  data:
    mongodb:
      database: customerdb
      port: '27017'
      host: localhost
logging:
  level:
    com.bank.customer: DEBUG
